server:
  port: 8767
spring:
  application:
    name: eureka-ribbon-client-without
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka,http://peer2:8762/eureka,http://peer3:8763/eureka
    healthcheck:
      enabled: true #注册中心健康检查
  instance:
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: 6

stores:
  ribbon:
    listOfServers: example.com,google.com
ribbon:
  eureka:
    enabled: false