spring:
  application:
    name: service-turbine
server:
  port: 8769
turbine:
  aggregator:
    clusterConfig: default
  appConfig: eureka-ribbon-client,eureka-feign-client
  clusterNameExpression: new String("default")
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka
    healthcheck:
      enabled: true #注册中心健康检查
    instance:
      lease-renewal-interval-in-seconds: 2
      lease-expiration-duration-in-seconds: 6