#读取本地配置文件
#server:
#  port: 8000
#spring:
#  profiles:
#    active: native
#  application:
#    name: config-server
#  cloud:
#    config:
#      server:
#        native:
#          search-locations: classpath:/shared
#
#

#读取配置中心配置文件
server:
  port: 8000
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/NullPointer8023/config-files.git
          search-paths: dev
          username:
          password:
      label: master
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
    bus-refresh:
      enabled: true